set birthdayMessage ("Happy Birthday!")

Mail from anonym@mail.com:

    schedule @ [29/02/2020, 00:00]:
        send [birthdayMessage] to [(friend@mail.com)]
    end schedule
    
    schedule @ [29/02/2021, 00:00]:
        send [birthdayMessage] to [(friend@mail.com)]
    end schedule

    schedule @ [29/02/2022, 00:00]:
        send [birthdayMessage] to [(friend@mail.com)]
    end schedule

    schedule @ [29/02/2023, 00:00]:
        send [birthdayMessage] to [(friend@mail.com)]
    end schedule
    
end Mail


